### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by quo91** [OPSkins/node-opskins-api#8]
So I'm using your API with the following code:

var OPSkinsAPI = require('@opskins/api');
var opskins = new OPSkinsAPI('a40af66c288875e51feed10a4a0776');
var appid = 753;
opskins.getLowestPrices(function(appid, prices) {
});

and when I execute it I get this error:
TypeError: callback is not a function
    at C:\Users\Jaka\Desktop\Bot\node_modules\@opskins\api\interfaces\IPricing.js:25:4
    at ClientRequest.<anonymous> (C:\Users\Jaka\Desktop\Bot\node_modules\@opskins\api\index.js:123:4)
    at ClientRequest.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)

**Comment by DoctorMcKay** [comment]
Your API key has been revoked since you posted it here.

As per the documentation, you need to supply an appid. For example:

```js
opskins.getLowestPrices(appid, function(err, prices) {
    // code
});
```

**Comment by quo91** [comment]
Thanks for your help! I really appreciate it! My app is allready done except for this last tiny part. I can't figure out how I would download a list of lowests prices for PUBG items and save them as a JSON file (LOCALLY). This process would be done every 30 min and the old JSON file would get written over.
